# Generated by Django 5.0.6 on 2024-07-06 05:15

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('work_time', models.CharField(max_length=200, verbose_name='Work Time')),
                ('work_time_en', models.CharField(max_length=200, null=True, verbose_name='Work Time')),
                ('work_time_uz', models.CharField(max_length=200, null=True, verbose_name='Work Time')),
                ('work_time_ru', models.CharField(max_length=200, null=True, verbose_name='Work Time')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('position_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='Position')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.about', verbose_name='About')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.language', verbose_name='Language')),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='languages',
            field=models.ManyToManyField(through='main.LanguageShip', to='main.language', verbose_name='Languages'),
        ),
    ]
