# Generated by Django 5.0.6 on 2024-11-24 17:52

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('full_name_uz', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='Full name')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('cv_file', models.FileField(upload_to='./cvfile/')),
                ('image', models.ImageField(upload_to='./image/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=50, verbose_name='Project Number')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Project Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Project Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Project Name')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('technology', models.CharField(max_length=100, verbose_name='Technology')),
                ('live_link', models.CharField(max_length=300, verbose_name='Project live link')),
                ('github_link', models.CharField(max_length=300, null=True, verbose_name='Project Github link')),
                ('image', models.ImageField(upload_to='./project/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Boxicons icon class')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('link', models.URLField(verbose_name='Link')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=100, verbose_name='Date day')),
                ('date_time_en', models.CharField(max_length=100, null=True, verbose_name='Date day')),
                ('date_time_uz', models.CharField(max_length=100, null=True, verbose_name='Date day')),
                ('date_time_ru', models.CharField(max_length=100, null=True, verbose_name='Date day')),
                ('direction', models.CharField(max_length=100, verbose_name="Yo'nalish")),
                ('direction_en', models.CharField(max_length=100, null=True, verbose_name="Yo'nalish")),
                ('direction_uz', models.CharField(max_length=100, null=True, verbose_name="Yo'nalish")),
                ('direction_ru', models.CharField(max_length=100, null=True, verbose_name="Yo'nalish")),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('company_en', models.CharField(max_length=100, null=True, verbose_name='Company')),
                ('company_uz', models.CharField(max_length=100, null=True, verbose_name='Company')),
                ('company_ru', models.CharField(max_length=100, null=True, verbose_name='Company')),
                ('content', models.TextField(verbose_name='Content')),
                ('content_en', models.TextField(null=True, verbose_name='Content')),
                ('content_uz', models.TextField(null=True, verbose_name='Content')),
                ('content_ru', models.TextField(null=True, verbose_name='Content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page', verbose_name='Experience or Education')),
            ],
        ),
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Type')),
                ('result', models.CharField(max_length=100, verbose_name='Content')),
                ('result_en', models.CharField(max_length=100, null=True, verbose_name='Content')),
                ('result_uz', models.CharField(max_length=100, null=True, verbose_name='Content')),
                ('result_ru', models.CharField(max_length=100, null=True, verbose_name='Content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('about_me', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page', verbose_name='About Me')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Skills Name')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Boxicons Icon Class')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.page', verbose_name='Skill')),
            ],
        ),
    ]
