# Generated by Django 5.0.6 on 2024-12-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=20)),
                ('base_en', models.CharField(max_length=20, null=True)),
                ('base_uz', models.CharField(max_length=20, null=True)),
                ('base_ru', models.CharField(max_length=20, null=True)),
                ('base_url', models.CharField(max_length=20)),
                ('base_url_en', models.CharField(max_length=20, null=True)),
                ('base_url_uz', models.CharField(max_length=20, null=True)),
                ('base_url_ru', models.CharField(max_length=20, null=True)),
                ('base_img', models.ImageField(upload_to='images/')),
                ('first', models.CharField(max_length=20)),
                ('first_en', models.CharField(max_length=20, null=True)),
                ('first_uz', models.CharField(max_length=20, null=True)),
                ('first_ru', models.CharField(max_length=20, null=True)),
                ('first_url', models.CharField(max_length=20)),
                ('first_url_en', models.CharField(max_length=20, null=True)),
                ('first_url_uz', models.CharField(max_length=20, null=True)),
                ('first_url_ru', models.CharField(max_length=20, null=True)),
                ('first_img', models.ImageField(upload_to='images/')),
                ('second', models.CharField(max_length=20)),
                ('second_en', models.CharField(max_length=20, null=True)),
                ('second_uz', models.CharField(max_length=20, null=True)),
                ('second_ru', models.CharField(max_length=20, null=True)),
                ('second_url', models.CharField(max_length=20)),
                ('second_url_en', models.CharField(max_length=20, null=True)),
                ('second_url_uz', models.CharField(max_length=20, null=True)),
                ('second_url_ru', models.CharField(max_length=20, null=True)),
                ('second_img', models.ImageField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
