# Generated by Django 5.0.6 on 2024-07-08 13:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('programs', models.ManyToManyField(blank=True, null=True, to='main.program')),
            ],
        ),
    ]
