# Generated by Django 5.0.6 on 2024-12-06 06:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_language_base_img_en_language_base_img_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Section Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Section Name')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Section Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Section Name')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
