# Generated by Django 5.0.6 on 2024-07-08 13:07

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='content_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='experience',
            name='content_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='experience',
            name='content_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
