# Generated by Django 5.0.6 on 2024-07-09 04:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_experience_content_en_experience_content_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='content')),
            ],
        ),
    ]
